# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/face_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/face_recognition.proto',
  package='FaceRecognition',
  syntax='proto3',
  serialized_options=b'\n\'com.pji.cloud.research.face.recognitionB\017FaceRecognitionP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dprotos/face_recognition.proto\x12\x0f\x46\x61\x63\x65Recognition\"3\n\x0b\x46\x61\x63\x65\x46\x65\x61ture\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\x0c\x12\x13\n\x0b\x66\x65\x61tureSize\x18\x02 \x01(\x05\"Y\n\x04\x46\x61\x63\x65\x12\x0e\n\x06\x66\x61\x63\x65Id\x18\x01 \x01(\t\x12\x0e\n\x06repoId\x18\x02 \x01(\t\x12\x31\n\x0b\x66\x61\x63\x65\x46\x65\x61ture\x18\x03 \x01(\x0b\x32\x1c.FaceRecognition.FaceFeature\">\n\rUploadRequest\x12\x0e\n\x06\x66\x61\x63\x65Id\x18\x01 \x01(\t\x12\x0e\n\x06repoId\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\".\n\rSearchRequest\x12\x0e\n\x06repoId\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"0\n\x0e\x43ompareRequest\x12\x0e\n\x06image1\x18\x01 \x01(\x0c\x12\x0e\n\x06image2\x18\x02 \x01(\x0c\"\x1a\n\x0bUploadReply\x12\x0b\n\x03rtn\x18\x01 \x01(\x05\",\n\x0bSimilarFace\x12\x0e\n\x06\x66\x61\x63\x65Id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"N\n\x0bSearchReply\x12\x0b\n\x03rtn\x18\x01 \x01(\x05\x12\x32\n\x0csimilarFaces\x18\x02 \x03(\x0b\x32\x1c.FaceRecognition.SimilarFace\"*\n\x0c\x43ompareReply\x12\x0b\n\x03rtn\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\"/\n\rDeleteRequest\x12\x0e\n\x06\x66\x61\x63\x65Id\x18\x01 \x01(\t\x12\x0e\n\x06repoId\x18\x02 \x01(\t2\x8c\x03\n\x15\x46\x61\x63\x65RecognitionEngine\x12H\n\x06Upload\x12\x1e.FaceRecognition.UploadRequest\x1a\x1c.FaceRecognition.UploadReply\"\x00\x12H\n\x06Search\x12\x1e.FaceRecognition.SearchRequest\x1a\x1c.FaceRecognition.SearchReply\"\x00\x12K\n\x07\x43ompare\x12\x1f.FaceRecognition.CompareRequest\x1a\x1d.FaceRecognition.CompareReply\"\x00\x12H\n\x06Update\x12\x1e.FaceRecognition.UploadRequest\x1a\x1c.FaceRecognition.UploadReply\"\x00\x12H\n\x06\x44\x65lete\x12\x1e.FaceRecognition.DeleteRequest\x1a\x1c.FaceRecognition.UploadReply\"\x00\x42<\n\'com.pji.cloud.research.face.recognitionB\x0f\x46\x61\x63\x65RecognitionP\x01\x62\x06proto3'
)




_FACEFEATURE = _descriptor.Descriptor(
  name='FaceFeature',
  full_name='FaceRecognition.FaceFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='FaceRecognition.FaceFeature.feature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='featureSize', full_name='FaceRecognition.FaceFeature.featureSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=101,
)


_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='FaceRecognition.Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='faceId', full_name='FaceRecognition.Face.faceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repoId', full_name='FaceRecognition.Face.repoId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='faceFeature', full_name='FaceRecognition.Face.faceFeature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=192,
)


_UPLOADREQUEST = _descriptor.Descriptor(
  name='UploadRequest',
  full_name='FaceRecognition.UploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='faceId', full_name='FaceRecognition.UploadRequest.faceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repoId', full_name='FaceRecognition.UploadRequest.repoId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='FaceRecognition.UploadRequest.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=256,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='FaceRecognition.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='repoId', full_name='FaceRecognition.SearchRequest.repoId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='FaceRecognition.SearchRequest.image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=304,
)


_COMPAREREQUEST = _descriptor.Descriptor(
  name='CompareRequest',
  full_name='FaceRecognition.CompareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image1', full_name='FaceRecognition.CompareRequest.image1', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image2', full_name='FaceRecognition.CompareRequest.image2', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=354,
)


_UPLOADREPLY = _descriptor.Descriptor(
  name='UploadReply',
  full_name='FaceRecognition.UploadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtn', full_name='FaceRecognition.UploadReply.rtn', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=382,
)


_SIMILARFACE = _descriptor.Descriptor(
  name='SimilarFace',
  full_name='FaceRecognition.SimilarFace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='faceId', full_name='FaceRecognition.SimilarFace.faceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='FaceRecognition.SimilarFace.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=428,
)


_SEARCHREPLY = _descriptor.Descriptor(
  name='SearchReply',
  full_name='FaceRecognition.SearchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtn', full_name='FaceRecognition.SearchReply.rtn', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='similarFaces', full_name='FaceRecognition.SearchReply.similarFaces', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=508,
)


_COMPAREREPLY = _descriptor.Descriptor(
  name='CompareReply',
  full_name='FaceRecognition.CompareReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtn', full_name='FaceRecognition.CompareReply.rtn', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='FaceRecognition.CompareReply.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=552,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='FaceRecognition.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='faceId', full_name='FaceRecognition.DeleteRequest.faceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repoId', full_name='FaceRecognition.DeleteRequest.repoId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=601,
)

_FACE.fields_by_name['faceFeature'].message_type = _FACEFEATURE
_SEARCHREPLY.fields_by_name['similarFaces'].message_type = _SIMILARFACE
DESCRIPTOR.message_types_by_name['FaceFeature'] = _FACEFEATURE
DESCRIPTOR.message_types_by_name['Face'] = _FACE
DESCRIPTOR.message_types_by_name['UploadRequest'] = _UPLOADREQUEST
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['CompareRequest'] = _COMPAREREQUEST
DESCRIPTOR.message_types_by_name['UploadReply'] = _UPLOADREPLY
DESCRIPTOR.message_types_by_name['SimilarFace'] = _SIMILARFACE
DESCRIPTOR.message_types_by_name['SearchReply'] = _SEARCHREPLY
DESCRIPTOR.message_types_by_name['CompareReply'] = _COMPAREREPLY
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaceFeature = _reflection.GeneratedProtocolMessageType('FaceFeature', (_message.Message,), {
  'DESCRIPTOR' : _FACEFEATURE,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.FaceFeature)
  })
_sym_db.RegisterMessage(FaceFeature)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), {
  'DESCRIPTOR' : _FACE,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.Face)
  })
_sym_db.RegisterMessage(Face)

UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREQUEST,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.UploadRequest)
  })
_sym_db.RegisterMessage(UploadRequest)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

CompareRequest = _reflection.GeneratedProtocolMessageType('CompareRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREREQUEST,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.CompareRequest)
  })
_sym_db.RegisterMessage(CompareRequest)

UploadReply = _reflection.GeneratedProtocolMessageType('UploadReply', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREPLY,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.UploadReply)
  })
_sym_db.RegisterMessage(UploadReply)

SimilarFace = _reflection.GeneratedProtocolMessageType('SimilarFace', (_message.Message,), {
  'DESCRIPTOR' : _SIMILARFACE,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.SimilarFace)
  })
_sym_db.RegisterMessage(SimilarFace)

SearchReply = _reflection.GeneratedProtocolMessageType('SearchReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREPLY,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.SearchReply)
  })
_sym_db.RegisterMessage(SearchReply)

CompareReply = _reflection.GeneratedProtocolMessageType('CompareReply', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREREPLY,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.CompareReply)
  })
_sym_db.RegisterMessage(CompareReply)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'protos.face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognition.DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)


DESCRIPTOR._options = None

_FACERECOGNITIONENGINE = _descriptor.ServiceDescriptor(
  name='FaceRecognitionEngine',
  full_name='FaceRecognition.FaceRecognitionEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=604,
  serialized_end=1000,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='FaceRecognition.FaceRecognitionEngine.Upload',
    index=0,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_UPLOADREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='FaceRecognition.FaceRecognitionEngine.Search',
    index=1,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Compare',
    full_name='FaceRecognition.FaceRecognitionEngine.Compare',
    index=2,
    containing_service=None,
    input_type=_COMPAREREQUEST,
    output_type=_COMPAREREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='FaceRecognition.FaceRecognitionEngine.Update',
    index=3,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_UPLOADREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='FaceRecognition.FaceRecognitionEngine.Delete',
    index=4,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=_UPLOADREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACERECOGNITIONENGINE)

DESCRIPTOR.services_by_name['FaceRecognitionEngine'] = _FACERECOGNITIONENGINE

# @@protoc_insertion_point(module_scope)
