# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lprnet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lprnet.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\200\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clprnet.proto\"\x1f\n\rLprnetRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\" \n\x0eLprnetResponse\x12\x0e\n\x06labels\x18\x01 \x03(\t2=\n\rLprnetService\x12,\n\x07predict\x12\x0e.LprnetRequest\x1a\x0f.LprnetResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3'
)




_LPRNETREQUEST = _descriptor.Descriptor(
  name='LprnetRequest',
  full_name='LprnetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='LprnetRequest.images', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=47,
)


_LPRNETRESPONSE = _descriptor.Descriptor(
  name='LprnetResponse',
  full_name='LprnetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='LprnetResponse.labels', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['LprnetRequest'] = _LPRNETREQUEST
DESCRIPTOR.message_types_by_name['LprnetResponse'] = _LPRNETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LprnetRequest = _reflection.GeneratedProtocolMessageType('LprnetRequest', (_message.Message,), {
  'DESCRIPTOR' : _LPRNETREQUEST,
  '__module__' : 'lprnet_pb2'
  # @@protoc_insertion_point(class_scope:LprnetRequest)
  })
_sym_db.RegisterMessage(LprnetRequest)

LprnetResponse = _reflection.GeneratedProtocolMessageType('LprnetResponse', (_message.Message,), {
  'DESCRIPTOR' : _LPRNETRESPONSE,
  '__module__' : 'lprnet_pb2'
  # @@protoc_insertion_point(class_scope:LprnetResponse)
  })
_sym_db.RegisterMessage(LprnetResponse)


DESCRIPTOR._options = None

_LPRNETSERVICE = _descriptor.ServiceDescriptor(
  name='LprnetService',
  full_name='LprnetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=83,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='LprnetService.predict',
    index=0,
    containing_service=None,
    input_type=_LPRNETREQUEST,
    output_type=_LPRNETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LPRNETSERVICE)

DESCRIPTOR.services_by_name['LprnetService'] = _LPRNETSERVICE

# @@protoc_insertion_point(module_scope)
