# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plate.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\200\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bplate.proto\"\x1d\n\x0cPlateRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"@\n\x04Rect\x12\x0c\n\x04left\x18\x01 \x01(\x02\x12\r\n\x05right\x18\x02 \x01(\x02\x12\x0b\n\x03top\x18\x03 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x02\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"y\n\x0bPlate4Point\x12\x17\n\x07topleft\x18\x01 \x01(\x0b\x32\x06.Point\x12\x18\n\x08topright\x18\x02 \x01(\x0b\x32\x06.Point\x12\x1a\n\nbottomleft\x18\x03 \x01(\x0b\x32\x06.Point\x12\x1b\n\x0b\x62ottomright\x18\x04 \x01(\x0b\x32\x06.Point\"I\n\x05Plate\x12\r\n\x05score\x18\x01 \x01(\x02\x12\x13\n\x04rect\x18\x02 \x01(\x0b\x32\x05.Rect\x12\x1c\n\x06points\x18\x03 \x01(\x0b\x32\x0c.Plate4Point\"\'\n\rPlateResponse\x12\x16\n\x06Plates\x18\x01 \x03(\x0b\x32\x06.Plate2:\n\x0cPlateService\x12*\n\x07predict\x12\r.PlateRequest\x1a\x0e.PlateResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3'
)




_PLATEREQUEST = _descriptor.Descriptor(
  name='PlateRequest',
  full_name='PlateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='PlateRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=44,
)


_RECT = _descriptor.Descriptor(
  name='Rect',
  full_name='Rect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='Rect.left', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right', full_name='Rect.right', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top', full_name='Rect.top', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='Rect.bottom', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=110,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=141,
)


_PLATE4POINT = _descriptor.Descriptor(
  name='Plate4Point',
  full_name='Plate4Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topleft', full_name='Plate4Point.topleft', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topright', full_name='Plate4Point.topright', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottomleft', full_name='Plate4Point.bottomleft', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottomright', full_name='Plate4Point.bottomright', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=264,
)


_PLATE = _descriptor.Descriptor(
  name='Plate',
  full_name='Plate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='Plate.score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rect', full_name='Plate.rect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points', full_name='Plate.points', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=339,
)


_PLATERESPONSE = _descriptor.Descriptor(
  name='PlateResponse',
  full_name='PlateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Plates', full_name='PlateResponse.Plates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=380,
)

_PLATE4POINT.fields_by_name['topleft'].message_type = _POINT
_PLATE4POINT.fields_by_name['topright'].message_type = _POINT
_PLATE4POINT.fields_by_name['bottomleft'].message_type = _POINT
_PLATE4POINT.fields_by_name['bottomright'].message_type = _POINT
_PLATE.fields_by_name['rect'].message_type = _RECT
_PLATE.fields_by_name['points'].message_type = _PLATE4POINT
_PLATERESPONSE.fields_by_name['Plates'].message_type = _PLATE
DESCRIPTOR.message_types_by_name['PlateRequest'] = _PLATEREQUEST
DESCRIPTOR.message_types_by_name['Rect'] = _RECT
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Plate4Point'] = _PLATE4POINT
DESCRIPTOR.message_types_by_name['Plate'] = _PLATE
DESCRIPTOR.message_types_by_name['PlateResponse'] = _PLATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlateRequest = _reflection.GeneratedProtocolMessageType('PlateRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLATEREQUEST,
  '__module__' : 'plate_pb2'
  # @@protoc_insertion_point(class_scope:PlateRequest)
  })
_sym_db.RegisterMessage(PlateRequest)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), {
  'DESCRIPTOR' : _RECT,
  '__module__' : 'plate_pb2'
  # @@protoc_insertion_point(class_scope:Rect)
  })
_sym_db.RegisterMessage(Rect)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'plate_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  })
_sym_db.RegisterMessage(Point)

Plate4Point = _reflection.GeneratedProtocolMessageType('Plate4Point', (_message.Message,), {
  'DESCRIPTOR' : _PLATE4POINT,
  '__module__' : 'plate_pb2'
  # @@protoc_insertion_point(class_scope:Plate4Point)
  })
_sym_db.RegisterMessage(Plate4Point)

Plate = _reflection.GeneratedProtocolMessageType('Plate', (_message.Message,), {
  'DESCRIPTOR' : _PLATE,
  '__module__' : 'plate_pb2'
  # @@protoc_insertion_point(class_scope:Plate)
  })
_sym_db.RegisterMessage(Plate)

PlateResponse = _reflection.GeneratedProtocolMessageType('PlateResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLATERESPONSE,
  '__module__' : 'plate_pb2'
  # @@protoc_insertion_point(class_scope:PlateResponse)
  })
_sym_db.RegisterMessage(PlateResponse)


DESCRIPTOR._options = None

_PLATESERVICE = _descriptor.ServiceDescriptor(
  name='PlateService',
  full_name='PlateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=382,
  serialized_end=440,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='PlateService.predict',
    index=0,
    containing_service=None,
    input_type=_PLATEREQUEST,
    output_type=_PLATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLATESERVICE)

DESCRIPTOR.services_by_name['PlateService'] = _PLATESERVICE

# @@protoc_insertion_point(module_scope)
